#!/usr/bin/env python3

from lib.gekko.report import Report
import argparse

def parse_command_line():
  opts = argparse.ArgumentParser(
    prog='Gekko',
    description='Reporting and munging tool for stock data',
    epilog='Remember: a fool and his money are soon parted'
  )

  opts.add_argument("report", help="The report definition file to run")
  return opts.parse_args()

args = parse_command_line()
report = Report.load_file(args.report)

print(report.text())
