#!/usr/bin/env python3
from lib.gekko.config import load_config
from lib.gekko.report import Report
from lib.gekko.view import View
import argparse

def parse_command_line():
  opts = argparse.ArgumentParser(
    prog='Gekko',
    description='Reporting and munging tool for stock data',
    epilog='Remember: a fool and his money are soon parted'
  )

  opts.add_argument("report", help="The report definition file to run")
  opts.add_argument("-t", "--usetabs", action='store_true')
  return opts.parse_args()

args = parse_command_line()
config = load_config(args.report)
view = View(config, args)
report = Report(config)

print(view.text(report))
